log:
  level: 10
  name: pi-relay-controller

db:
  filename: ./db.json

gpio:
  relays:
    - relay: 1
      gpio: GPIO_19
      name: Relay 1
      pin: 35
    - relay: 2
      gpio: GPIO_13
      name: Relay 2
      pin: 33
    - relay: 3
      gpio: GPIO_6
      name: Relay 3
      pin: 31
    - relay: 4
      gpio: GPIO_5
      name: Relay 4
      pin: 29
  default: NO

ssl:
  secure: true             # true to prefer to create a server that accepts SSL connections
  fallbackToInsecure: true # fallback to insecure if for some reason we can't create a secure server
  defaults:
    - name: 'commonName'
      value: dummy.org
  options: !!map { keySize: 2048, days: 3650, clientCertificate: false, pkcs7: false }

gRPC:
  server:
    host: localhost
    portSecure: 50051
    portInsecure: 50051

bonjour:
  name: pi-relay-controller-server
