log:
  # Log levels are:
  # 'fatal' (60)
  # 'error' (50)
  # 'warn'  (40)
  # 'info'  (30)
  # 'debug' (20)
  # 'trace' (10)
  level: 10
  name: pi-relay-controller

db:
  filename: ./db.json

gpio:
  relays:
    - relay: 1
      gpio: GPIO_19
      name: Relay 1
      pin: 35
      state: 0
    - relay: 2
      gpio: GPIO_13
      name: Relay 2
      pin: 33
      state: 0
    - relay: 3
      gpio: GPIO_6
      name: Relay 3
      pin: 31
      state: 0
    - relay: 4
      gpio: GPIO_5
      name: Relay 4
      pin: 29
      state: 0

gRPC:
  server:
    host: 192.168.1.149
    port: 50051

initialState: off
